name: CI

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:

    # This job runs on a Linux machine
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Echo a statement
      run: echo "Hello GitHub Actions!"
